spring:
  application:
    name: product-service


  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo:27018/product_db?replicaSet=rs0}

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_ACCESS_SECRET}

server:
  port: 8085
  servlet:
    context-path: /api/v1/products

gcp:
  bucket-name: ${GCP_BUCKET_NAME:my-product-img}
  config-path: ${GCP_CONFIG_PATH}

jwt:
  access-secret: ${JWT_ACCESS_SECRET}

app:
  ticket-service-url: ${TICKET_SERVICE_URL:http://ticket-service:8083}
